### ISSUE TITLE
createShape() returning None

### ISSUE THREAD

**Issue by baronvonbadguy** [jdf/Processing.py-Bugs#121]
I don't know how else to describe this bug, but currently every time I call createShape(), using any shape mode including none, the function returns a None object.  I'm using build 402, and I haven't come across any similar issue in this issue repo nor the original repo.

Using this throws a NoneType s has no attribute beginShape()

    s = createShape()
    s.beginShape()

I would like to be able to do something like

    class TrochoidShape():
        
        def  __init__(self):
            self.trochoid = createShape()

        def generate_vertices(self):
            with self.trochoid.beginShape():
                for angle in range(0,360):
                    pos = (x_formula(angle), y_formula(angle))
                    self.trochoid.vertex(*pos)
        
        def render(self):
            with pushMatrix():
                shape(self.trochoid)
But instead I have to do something like

    class TrochoidShape():
        
        def  __init__(self):
            self.points = list()

        def generate_vertices(self):
            with self.trochoid.beginShape():
                for angle in range(0,360):
                    pos = (x_formula(angle), y_formula(angle))
                    self.points.append(pos)
        
        def render(self):
            with pushMatrix():
                with beginShape():
                    for pos in self.points:
                        vertex(*pos)
The latter option will draw as I want it to, but I have no ability to retain that PShape in the namespace.  This seems like a less than ideal scenario, and I'm not sure what I'm doing wrong.  It seems to me like I'm missing something obvious.

EDIT: sorry about closing the issue I must have accidentally hit the button.

**Comment by jdf** [comment]
This program

```python
s = createShape()
print s
```

gives me the expected output `processing.core.PShape@17359c0b`. Can you post a minimal, but complete, Processing program that exhibits the behavior you're seeing?

**Comment by baronvonbadguy** [comment]
Here's the doodle I was working on that sparked this.  Does it have to do with the non-static reference to self?  

    class Trochoid():
        'Class for creating and rendering a trochoid'
        def __init__(self, primary=200, secondary=5, tertiary=100, resolution=1, offset=0):
            self.primary = float(primary)
            self.secondary = float(secondary)
            self.tertiary = float(tertiary)
            self.pshape = createShape()
            
        def generate_points(self):
            #intialize location variables and primary, secondary, and tertiary radii
            x, y = 0, 0
            p, s, t = self.primary, self.secondary, self.tertiary
            rad_range = (radians(ang) for ang in range(0.0, 360.0))
            with self.pshape.beginShape():
                stroke(100, 100, 100)
                noFill()
                for rad in rad_range:
                    x = ((p - s) * cos(rad) + (t * cos((p - s)/(s) * rad)))
                    y = ((p - s) * sin(rad) - (t * sin((p - s)/(s) * rad)))
                    self.pshape.vertex(x, y)
            
        def render(self):
            with pushMatrix():
                translate(width/2, height/2)
                shape(self.pshape)

    troch = Trochoid()

    def setup():
        size(1280, 720)
        colorMode(HSB)

    def draw():
        background(10, 10, 10)
        troch.primary = map(mouseX, 0, width, 100, 800)
        troch.secondary = map(mouseY, 0, height, .0001, 5)
        troch.generate_points()
        troch.render()

Running this gives me the following stack trace

    processing.app.SketchException: java.lang.NullPointerException
        at processing.core.PApplet.createShape(PApplet.java:11667)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
        at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
        at org.python.core.PyObject.__call__(PyObject.java:403)
        at org.python.core.PyObject.__call__(PyObject.java:407)
        at org.python.core.PyMethod.__call__(PyMethod.java:121)
        at Trochoid$py.__init__$2(/home/sunshine/sketchbook/trochoid_generator_python/Trochoid.py:7)
        at Trochoid$py.call_function(/home/sunshine/sketchbook/trochoid_generator_python/Trochoid.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:165)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:194)
        at org.python.core.PyFunction.__call__(PyFunction.java:417)
        at org.python.core.PyFunction.__call__(PyFunction.java:411)
        at org.python.core.PyInstance.__init__(PyInstance.java:120)
        at org.python.core.PyClass.__call__(PyClass.java:194)
        at org.python.core.PyObject.__call__(PyObject.java:387)
        at org.python.core.PyObject.__call__(PyObject.java:391)
        at org.python.pycode._pyx62.f$0(/home/sunshine/sketchbook/trochoid_generator_python/trochoid_generator_python.pyde:16)
        at org.python.pycode._pyx62.call_function(/home/sunshine/sketchbook/trochoid_generator_python/trochoid_generator_python.pyde)
        at org.python.core.PyTableCode.call(PyTableCode.java:165)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1312)
        at org.python.core.Py.exec(Py.java:1356)
        at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:215)
        at jycessing.PAppletJythonDriver.processSketch(Unknown Source)
        at jycessing.PAppletJythonDriver.findSketchMethods(Unknown Source)
        at jycessing.Runner.runSketchBlocking(Unknown Source)
        at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

        at jycessing.mode.run.SketchRunner.convertPythonSketchError(Unknown Source)
        at jycessing.mode.run.SketchRunner.access$300(Unknown Source)
        at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by baronvonbadguy** [comment]
Here's a minimal example.

	class Bug():
	    def __init__(self):
	        self.pshape = createShape()

	    def generate_points(self):
	        with self.pshape.beginShape():
	            for x in range(20):
	                self.pshape.vertex(x, x)

	    def render(self):
	        with pushMatrix():
	            translate(width/2, height/2)
	            shape(self.pshape)

	bug = Bug()

	def setup():
	    size(1280, 720)
	    colorMode(HSB)

	def draw():
	    bug.generate_points()
	    bug.render()

This generates the following stack trace

	processing.app.SketchException: java.lang.NullPointerException
		at processing.core.PApplet.createShape(PApplet.java:11667)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
		at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
		at org.python.core.PyObject.__call__(PyObject.java:403)
		at org.python.core.PyObject.__call__(PyObject.java:407)
		at org.python.core.PyMethod.__call__(PyMethod.java:121)
		at org.python.pycode._pyx13.__init__$2(/tmp/sketch_150119d5928620902333621623/sketch_150119d.pyde:3)
		at org.python.pycode._pyx13.call_function(/tmp/sketch_150119d5928620902333621623/sketch_150119d.pyde)
		at org.python.core.PyTableCode.call(PyTableCode.java:165)
		at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
		at org.python.core.PyBaseCode.call(PyBaseCode.java:194)
		at org.python.core.PyFunction.__call__(PyFunction.java:417)
		at org.python.core.PyFunction.__call__(PyFunction.java:411)
		at org.python.core.PyInstance.__init__(PyInstance.java:120)
		at org.python.core.PyClass.__call__(PyClass.java:194)
		at org.python.core.PyObject.__call__(PyObject.java:387)
		at org.python.core.PyObject.__call__(PyObject.java:391)
		at org.python.pycode._pyx13.f$0(/tmp/sketch_150119d5928620902333621623/sketch_150119d.pyde:21)
		at org.python.pycode._pyx13.call_function(/tmp/sketch_150119d5928620902333621623/sketch_150119d.pyde)
		at org.python.core.PyTableCode.call(PyTableCode.java:165)
		at org.python.core.PyCode.call(PyCode.java:18)
		at org.python.core.Py.runCode(Py.java:1312)
		at org.python.core.Py.exec(Py.java:1356)
		at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:215)
		at jycessing.PAppletJythonDriver.processSketch(Unknown Source)
		at jycessing.PAppletJythonDriver.findSketchMethods(Unknown Source)
		at jycessing.Runner.runSketchBlocking(Unknown Source)
		at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)

		at jycessing.mode.run.SketchRunner.convertPythonSketchError(Unknown Source)
		at jycessing.mode.run.SketchRunner.access$300(Unknown Source)
		at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)

**Comment by jdf** [comment]
You can't call `createShape()` outside of the `setup()` function or the draw loop unless you're a completely static mode sketch. If it's an active mode sketch, i.e., has a `draw()` and/or a `setup()`, then there is no Processing graphics context when `createShape()` is called, and PApplet crashes. Observe that this does work:

```python
class Bug():
    def __init__(self):
        self.pshape = createShape()

def setup():
    global bug
    bug = Bug()
    pass

def draw():
    pass
```

**Comment by jdf** [comment]
Further note:

In Java mode, this sketch runs:

```java
PShape s = createShape();
```

while this one crashes in exactly the same way:

```java
PShape s = createShape();

void setup() {
}
```
