### ISSUE TITLE
The MidiBus Library Not Working

### ISSUE THREAD

**Issue by jcordiner** [jdf/Processing.py-Bugs#125]
On Processing 2.2.1 under OS X 10.9.5. Trying to use MIDI through the library The MidiBus. After adding the library with:

add_library('themidibus')

and running I get the following error message:

processing.app.SketchException: mismatched input '-' expecting NEWLINE
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:234)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:221)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:117)
	at java.lang.Thread.run(Thread.java:745)

Any help would be appreciated.

**Comment by jdf** [comment]
When I run the following sketch:
```python
add_library('themidibus')
```
It works just fine. Please paste the actual code that's not working for you.

**Comment by jcordiner** [comment]
It works fine for me on Windows. 

But on OS X 10.9.5 with Processing 2.2.1 it gives me an error. I ended up cutting out any code that might be causing any other problems - in the end just importing the library will produce the error: 

`add_library('themidibus')`

processing.app.SketchException: mismatched input '-' expecting NEWLINE
at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:234)
at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:221)
at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:117)
at java.lang.Thread.run(Thread.java:745)

**Comment by jdf** [comment]
I notice that there is no code at [line 221 in SketchRunner](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/mode/run/SketchRunner.java#L221). Are you sure your Python mode is up to date?

**Comment by jcordiner** [comment]
My bad, sorry about that. Didn't realize I was running an older Python mode - updated and error gone.

Thanks!

**Comment by jdf** [comment]
No problem! Thanks for taking the time.
