### ISSUE TITLE
Weird `lerpColor` behavior.

### ISSUE THREAD

**Issue by tildebyte** [jdf/Processing.py-Bugs#127]
Is this normal behavior? It only seems to happen if `lerpColor` is called from **outside** of a `def` *iff* there is a `setup()/draw()` type structure.

Recasting [this](http://py.processing.org/reference/lerpColor.html) example as[1]

````python
fromC = color(204, 102, 0)
toC = color(0, 102, 153)
interA = lerpColor(fromC, toC, .33)
interB = lerpColor(fromC, toC, .66)

def setup():
    background(51)

def draw():
    fill(fromC)
    rect(10, 20, 20, 60)
    fill(interA)
    rect(30, 20, 20, 60)
    fill(interB)
    rect(50, 20, 20, 60)
    fill(toC)
    rect(70, 20, 20, 60)

````

yields

````
processing.app.SketchException: java.lang.NullPointerException
	at processing.core.PApplet.lerpColor(PApplet.java:15548)
	at jycessing.PAppletJythonDriver$20.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyObject.__call__(PyObject.java:469)
	at org.python.pycode._pyx13.f$0(C:\Users\~\AppData\Local\Temp\sketcha7327059289860120850\sketcha.pyde:9)
	at org.python.pycode._pyx13.call_function(C:\Users\~\AppData\Local\Temp\sketcha7327059289860120850\sketcha.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:166)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1372)
	at org.python.core.Py.exec(Py.java:1416)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:279)
	at jycessing.PAppletJythonDriver.processSketch(Unknown Source)
	at jycessing.PAppletJythonDriver.findSketchMethods(Unknown Source)
	at jycessing.Runner.runSketchBlocking(Unknown Source)
	at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(Unknown Source)
	at jycessing.mode.run.SketchRunner.access$300(Unknown Source)
	at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

````

[1]Running it with `lerpColor` inside of `setup()` or `draw()` works as expected.

**Comment by jdf** [comment]
Yuck. No, not desirable.

**Comment by jdf** [comment]
Fixed in 0407.

**Comment by jdf** [comment]
By the way, this behavior is also broken in Java mode.

```java
color c = lerpColor(0, 100, .5);  // boom! crashes.

void setup() {}  // unless you comment this out
```

**Comment by tildebyte** [comment]
LOL
