### ISSUE TITLE
random.randint(-0, 0) throws an error instead of returning 0

### ISSUE THREAD

**Issue by virgiliu** [jdf/Processing.py-Bugs#130]
Sketch:

    import random
    import sys

    def setup():
        print(sys.version)
        print(random.randint(-0,0))

Output:

    2.7b4+ (default:6e8e76987965+, Jan 19 2015, 15:19:30) 
    [Java HotSpot(TM) Client VM (Oracle Corporation)]
    processing.app.SketchException: ValueError: math domain error
    	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:235)
    	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:222)
    	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:117)
    	at java.lang.Thread.run(Unknown Source)

Running `random.randint(-0,0)` directly in Python 2.7.3 console outputs 0.

**Comment by jdf** [comment]
Fixed in build 0409.
