### ISSUE TITLE
Using example OpenCV/LiveCamTest throws error

### ISSUE THREAD

**Issue by fabiantheblind** [jdf/Processing.py-Bugs#132]
When trying to run LiveCamTest I get the following error message:  

    processing.app.SketchException: AttributeError: 'NoneType' object has no attribute 'loadImage'
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:243)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:222)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:117)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jdf** [comment]
The example is missing some `global` statements.

**Comment by fabiantheblind** [comment]
aaaaahh now I get it. :+1: Thank you
