### ISSUE TITLE
Cannot install with Processing 2.0.3

### ISSUE THREAD

**Issue by jdeisenberg** [jdf/Processing.py-Bugs#134]
Download succeeds; then this error appears:
````
java.lang.UnsupportedClassVersionError: jycessing/mode/PythonMode : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at processing.app.contrib.ModeContribution.<init>(ModeContribution.java:78)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:45)
	at processing.app.contrib.ModeContribution.load(ModeContribution.java:38)
	at processing.app.contrib.ContributionType.load(ContributionType.java:183)
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:121)
	at processing.app.contrib.ContributionManager$1.run(ContributionManager.java:125)
	at java.lang.Thread.run(Thread.java:662)
java.lang.NullPointerException
	at processing.app.contrib.AvailableContribution.install(AvailableContribution.java:125)
	at processing.app.contrib.ContributionManager$1.run(ContributionManager.java:125)
	at java.lang.Thread.run(Thread.java:662)
````
I suspect it has something to do with my version of Java:

````
C:\Users\linux16>java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
````

**Comment by jdf** [comment]
It may be that you need 2.1 or better. I haven't tested with earlier versions.
