### ISSUE TITLE
Exporting 64 bit with Java does not create exe

### ISSUE THREAD

**Issue by ruyimarone** [jdf/Processing.py-Bugs#136]
When I export to a 64-bit exe and check embed java, I get two folders. The 32 bit folder has an exe in it, but the 64 bit does not. I am running windows 8.1, and using Processing 2.2.1. I found [this post](http://forum.processing.org/two/discussion/12190/can-processing-python-mode-export-x64-application), which describes the problem, but no solution. Am I misunderstanding something, or is there an actual issue? Thanks!

**Comment by jdf** [comment]
It sounds like a real problem. I didn't write the exporter, nor do I know much about it. I'll try to get the attention of the person who wrote it.

**Comment by jdf** [comment]
@kazimuth

**Comment by kazimuth** [comment]
Unfortunately I don't currently have access to a windows machine to mess with this on. In the meantime you can uncheck "embed java".

Are you running 64-bit processing? If so, I suspect the problem is that [launch4j](http://launch4j.sourceforge.net/) is failing to embed the JRE for some reason - possibly because the configuration we're passing it is somehow invalid.

@jdf, the relevant code is in [`WindowsExport.java`](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/mode/export/WindowsExport.java), which aside from creating the basic folder structure for the export, creates an XML configuration file and runs Processing's bundled launch4j executable on it. The code that specifically handles a bundled 64 bit JRE is [here](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/mode/export/WindowsExport.java#L196). It's possible we're just missing a [`<bundledJre64Bit>true</bundledJre64Bit>`](http://launch4j.sourceforge.net/docs.html) tag.

**Comment by Jshap06** [comment]
It seems that this issue was never resolved. Even now, four years later I'm having this very issue. I would greatly appreciate a fix.

**Comment by villares** [comment]
> Unfortunately I don't currently have access to a windows machine to mess with this on. In the meantime you can uncheck "embed java".
> 
> Are you running 64-bit processing? If so, I suspect the problem is that [launch4j](http://launch4j.sourceforge.net/) is failing to embed the JRE for some reason - possibly because the configuration we're passing it is somehow invalid.
> 
> @jdf, the relevant code is in [`WindowsExport.java`](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/mode/export/WindowsExport.java), which aside from creating the basic folder structure for the export, creates an XML configuration file and runs Processing's bundled launch4j executable on it. The code that specifically handles a bundled 64 bit JRE is [here](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/mode/export/WindowsExport.java#L196). It's possible we're just missing a [`<bundledJre64Bit>true</bundledJre64Bit>`](http://launch4j.sourceforge.net/docs.html) tag.

Hi @kazimuth, I suppose this would be very hard to come back to, but Is there perhaps someone you could coach into solving this? Just to check the problem, could you perhaps try a VM?

This is what we get with the embed option checked (also the 32bit version exports fine, but Processing 4 will abandon 32bit support) it would be so nice if you could make it work again for Processing 4... :

```
Export to windows64 failed!

java.io.IOException: Launch4j seems to have failed.
	at jycessing.mode.export.WindowsExport.runLaunch4j(Unknown Source)
	at jycessing.mode.export.WindowsExport.export(Unknown Source)
	at jycessing.mode.export.Exporter.export(Unknown Source)
	at jycessing.mode.export.ExportDialog.go(Unknown Source)
	at jycessing.mode.PyEditor.handleExportApplication(Unknown Source)
	at jycessing.mode.PyEditor$3.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
