### ISSUE TITLE
Python mode fails on Ubuntu 14.04.4

### ISSUE THREAD

**Issue by schuelaw** [jdf/Processing.py-Bugs#152]
A bit desperate here.  I have python mode (latest) running with processing (latest, 3.0.2) on Ubuntu 14.04.4 (fully patched), oracle java (fully patched).  

Java mode scripts run fine.  Switch to python mode, IDE appears, but with lots of errors on the console (see below).  Try to execute a script, e.g.:

ellipse(10,10,10,10)

more console errors (see below), but won't pop up the canvas.  Trying to use this in intro programming class Thu, any advice?  BTW, it works fine on my office machine (also Ubuntu 14.04.4 fully patched and what I think should be an identical environment).  What am I missing?

Here are the console errors:

`(markweiser)/usr/local/processing-3.0.2> Exception in thread "main" java.lang.RuntimeException: jycessing.mode.run.RMIUtils$RMIProblem: java.rmi.ConnectException: Connection refused to host: 10.33.1.131; nested exception is: 
	java.net.ConnectException: Connection refused
	at jycessing.mode.run.SketchRunner.startSketchRunner(SketchRunner.java:203)
	at jycessing.mode.run.SketchRunner.main(SketchRunner.java:167)
Caused by: jycessing.mode.run.RMIUtils$RMIProblem: java.rmi.ConnectException: Connection refused to host: 10.33.1.131; nested exception is: 
	java.net.ConnectException: Connection refused
	at jycessing.mode.run.RMIUtils.lookup(RMIUtils.java:91)
	at jycessing.mode.run.SketchRunner.startSketchRunner(SketchRunner.java:200)
	... 1 more
Caused by: java.rmi.ConnectException: Connection refused to host: 10.33.1.131; nested exception is: 
	java.net.ConnectException: Connection refused
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
	at jycessing.mode.run.RMIUtils.lookup(RMIUtils.java:89)
	... 2 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 7 more
`

**Comment by schuelaw** [comment]
This happens right before the java errors:
`aws@localhost:~# Traceback (most recent call last):
  File "/root/sketchbook/modes/PythonMode/formatter/format_server.py", line 12, in <module>
    sock.bind(server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
`

**Comment by schuelaw** [comment]
Figured it out!  My lab machines were misconfigured.  The hostname in /etc/hosts did not have the correct associate ip address.  Sorry to have wasted anyone's time.  Close this thing.

**Comment by jdf** [comment]
Thanks for your followups, and I'm glad all is well!
