### ISSUE TITLE
Python cannot run on Win 10 x64 / Processing 3.2.3

### ISSUE THREAD

**Issue by 13127975605** [jdf/Processing.py-Bugs#177]
Python mode was added to Processing 3.2.3, but codes cannot be run. Error is as below. Who can help? I'm a fresh hand.

processing.app.SketchException: Exception creating connection to: 127.0.0.1; nested exception is: 
	java.net.SocketException: Malformed reply from SOCKS server
	at jycessing.mode.run.SketchServiceProcess.handleRemoteException(SketchServiceProcess.java:88)
	at jycessing.mode.run.SketchServiceProcess.runSketch(SketchServiceProcess.java:194)
	at jycessing.mode.run.SketchServiceProcess$2.run(SketchServiceProcess.java:177)
	at jycessing.mode.run.SketchServiceProcess.handleReady(SketchServiceProcess.java:99)
	at jycessing.mode.run.SketchServiceManager.handleReady(SketchServiceManager.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
processing.app.SketchException: Exception creating connection to: 127.0.0.1; nested exception is: 
	java.net.SocketException: Malformed reply from SOCKS server
	at jycessing.mode.run.SketchServiceProcess.handleRemoteException(SketchServiceProcess.java:88)
	at jycessing.mode.run.SketchServiceProcess.runSketch(SketchServiceProcess.java:194)
	at jycessing.mode.run.SketchServiceProcess$2.run(SketchServiceProcess.java:177)
	at jycessing.mode.run.SketchServiceProcess.handleReady(SketchServiceProcess.java:99)
	at jycessing.mode.run.SketchServiceManager.handleReady(SketchServiceManager.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jdf** [comment]
I'm guessing there some firewall on your computer interfering with the TCP/IP networking that Python Mode uses to communicate with a separate process that actually runs the sketches.

**Comment by Bilalharoon** [comment]
i have the same problem

**Comment by anjchang** [comment]
Any suggestions on how I can instruct her to remove firewalls  just to install Python Mode and examples on Win7? I'm on a mac and don't have a win7 machine... Thank you for your help!

**Comment by osmancakir** [comment]
windows 10 here. display window is not coming up! even with the newest release!

**Comment by LaurentRenaud** [comment]
Hello everyone,

I'm a teacher, and I have the same problem with Processing 3.4 in my high school, on all the computers (windows 64 bits). Note that it works fine on my lapboard.

I read it mays come from the firewall, but how to solve this issue ? If someone has got a solution, I'd be grateful.

Thank you all,
Laurent
