### ISSUE TITLE
Problem in Scope deduction

### ISSUE THREAD

**Issue by Subh0m0y** [jdf/Processing.py-Bugs#178]
I have a variable named `tx` in the global scope of my file. I want to use it for the `noise()` function. However, when I try to use it, I'm getting an error:

```
processing.app.SketchException: UnboundLocalError: local variable 'tx' referenced before assignment
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(Unknown Source)
	at jycessing.mode.run.SketchRunner.access$300(Unknown Source)
	at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

My code (the relevant file) is:

```
from space import Region
from rain import *

initial = 600
drops = []

tx = 0
dt = 0.001


def setup():
    fullScreen()
    offset = height * 0.8
    region = Region(-offset, -offset, width + offset, height)

    count = max(height, initial)
    for _ in range(count):
        location = Vector2D(-offset + random(region.w), -random(offset))
        distance = random(mindist, maxdist)
        drops.append(Rain(location, distance, region, offset))


def draw():
    wind = Vector2D(noise(tx) * 0.1, 0)
    background(230, 210, 220)
    for drop in drops:
        drop.fall()
        drop.show()
        drop.applyforce(wind)
    tx = tx + dt
```

I think the problem is that `tx` is thought to be defined for the first time in `draw` because of the last line. Indeed, if I remove it, the code runs (i.e. compiles), but I don't get the ability to increment the time.

**Comment by jdf** [comment]
You need

```python
global tx
```

in `draw`.
