### ISSUE TITLE
Could not make Pickle work

### ISSUE THREAD

**Issue by villares** [jdf/Processing.py-Bugs#228]
Hi, maybe it's me but this is giving an error:

```
import pickle

A = "to be saved"
pickle.dump(A, open("variableA.p", "wb"))
A = "temp value"
print A
pickle.load(open("variableA.p", "rb"))
print A
```
The error is:
```
processing.app.SketchException: EOFError
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:244)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:125)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jdf** [comment]
I'm guessing it's because you're not closing the file.

**Comment by villares** [comment]
No error now :)  But it doesn't work (or I don't understand what I'm doing) :(

```
import pickle

A = ["to be saved"]
f = open("variableA.p", "wb")
pickle.dump(A, f)
f.close()

A = ["temp value"]
print A

f =  open("variableA.p", "rb")
pickle.load(f)
print A
f.close()
```

PS: I've tried the more elegant `with open( ... ) as f:` thing too

**Comment by jdf** [comment]
`A = pickle.load(f)`

**Comment by villares** [comment]
Thank you!!!
