### ISSUE TITLE
Auto Format java.net.ConnectExeption

### ISSUE THREAD

**Issue by villares** [jdf/Processing.py-Bugs#241]
I get this `java.net.ConnectException: Connection refused (Connection refused)`
and the formatting doesn't happen.
I've checked (turned off) the FIrewall but still can't make it work.
I don't know how to reproduce :(

**Comment by lhcui** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.syntax.PdeInputHandler.handleInputMethodCommit(PdeInputHandler.java:283)
	at processing.app.syntax.im.InputMethodSupport.inputMethodTextChanged(InputMethodSupport.java:194)
	at java.awt.Component.processInputMethodEvent(Component.java:6661)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by villares** [comment]
Working again, I have no idea of what happened.

**Comment by villares** [comment]
Not working...

```
created registry at port 8220
Traceback (most recent call last):
  File "/Users/ale/Documents/Processing/modes/PythonMode/formatter/format_server.py", line 12, in <module>
    sock.bind(server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
java.net.ConnectException: Connection refused (Connection refused)
```

**Comment by villares** [comment]
Hi @jdf , I now saw the same error message on a Windows 7 32-bit machine and on a Windows 10 machine. I have added Processing to the Firewall Exeption...

On a first try:
```
Traceback (most recent call last):
  File "C:\Users\Alexandre Villares\Documents\Processing\modes\PythonMode\formatter\format_server.py", line 34, in <module>
    connection.sendall(encoded)
  File "C:\Users\Alexandre Villares\Documents\Processing\modes\PythonMode\mode\jython.jar\Lib\_socket.py", line 1441, in meth
  File "C:\Users\Alexandre Villares\Documents\Processing\modes\PythonMode\mode\jython.jar\Lib\_socket.py", line 1484, in send
  File "C:\Users\Alexandre Villares\Documents\Processing\modes\PythonMode\mode\jython.jar\Lib\_socket.py", line 382, in handle_exception
  File "C:\Users\Alexandre Villares\Documents\Processing\modes\PythonMode\mode\jython.jar\Lib\_socket.py", line 382, in handle_exception
  File "C:\Users\Alexandre Villares\Documents\Processing\modes\PythonMode\mode\jython.jar\Lib\_socket.py", line 1200, in send
  File "C:\Users\Alexandre Villares\Documents\Processing\modes\PythonMode\mode\jython.jar\Lib\_socket.py", line 384, in handle_exception
_socket.error: [Errno 10054] Socket closed
````
At other times:
` java.net.ConnectException: Connection refused (Connection refused) `

What kind of log/report do you think might help us pinpoint this problem?

**Comment by jdf** [comment]
Processing is not the thing that needs to be added to the firewall exception, but rather the process launched by Python Mode. I have no idea how you'd identify that process to the firewall config, or whether it's even possible to do so, without granting permission to Java in general.
