### ISSUE TITLE
Python mode update | Error message

### ISSUE THREAD

**Issue by spprocessing** [jdf/Processing.py-Bugs#292]
Hi everyone,

Today (03/05/2020) I installed a new update for python mode in Processing, and, after that, I am having the following error message in the console every time I try to run the sketch.
I believe the problem is present because I am using in my sketch two libraries (Sound and PeasyCam), but before the update installation everything was just fine. Is this just a bug in the new update for Python mode? Am I supposed to do something different in this new update importing those libraries? I'll be very grateful If anyone can help me with this issue.

Error Message:

NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at jycessing.LibraryImporter.findResources(Unknown Source)
	at jycessing.LibraryImporter.recursivelyLoadNativeLibraryies(Unknown Source)
	at jycessing.LibraryImporter.addLibrary(Unknown Source)
	at jycessing.LibraryImporter$1.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
	at org.python.pycode._pyx11.f$0(spherical_phase_space.pyde:1)
	at org.python.pycode._pyx11.call_function(spherical_phase_space.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.pycode._pyx10.f$0(C:/Users/Samuel/OneDrive/TESE/spherical_phase_space/spherical_phase_space.pyde:96)
	at org.python.pycode._pyx10.call_function(C:/Users/Samuel/OneDrive/TESE/spherical_phase_space/spherical_phase_space.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at jycessing.PAppletJythonDriver.processSketch(Unknown Source)
	at jycessing.PAppletJythonDriver.findSketchMethods(Unknown Source)
	at jycessing.Runner.runSketchBlocking(Unknown Source)
	at jycessing.mode.run.SketchRunner.lambda$startSketch$3(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by villares** [comment]
Hi @spprocessing!

Please show us exactly how to reproduce this:
- OS (Mac, Windows, Linux?)
- Processing version (3.5.4?)
- Python mode build (3059?)
- Libraries (Which Sound library? Processing Foundation's?)
- This is crucial: *A minimal code sample that will trigger the problem* 
- Other relevant information (What did you update? One of the libraries?)
- Can you try using the backup of the older Python mode inside your `old` folder in `modes`?

Thank you!

**Comment by spprocessing** [comment]
Hi villares,

Thank you very much for your reply. Responding to your questions:
-  I'm using Windows OS;
- My Processing version is 3.5.4;
- Python mode build is 3059;
- I am using precisely the Sound library from Processing Foundation but I believe the problem happens when I import to my sketches any library. The problem persists with PeasyCam, for example.
- The code that seems to generate the problem is simply the code that imports the library when you select it in the import library menu inside the sketch tab. More precisely this section of the code:
`add_library('sound')`
`add_library('peasycam')`
It is very strange indeed because I was running the patch witohut any problem but as soon as I installed the Python mode update this problem appeared in all the sketches that use some kind of library.
- No. I only updated the Python mode for Processing. That was the only update that Processing was suggesting me.
- I didn't know it was possible to use older versions of the Python Mode. I found them as you suggested me in the Documents folder of Windows and using the previous version instantly solved the problem!

I have no idea if this is some kind of bug in the update, if the libraries are incompatible with it or any other issue but I thank you so very much for your assistance because I can now continue my work in the sketch.

Thank you!

**Comment by jdf** [comment]
@mpsftw was most recently in the import code path. Molly, is it possible that your recent work might have caused a regression for these libraries?

**Comment by mpsftw** [comment]
It's definitely possible. I'll take a look at it.

**Comment by mpsftw** [comment]
Y'all. Look at that sweet spelling error:
jycessing.LibraryImporter.recursivelyLoadNative**Libraryies**

That's 100% coming from me.

**Comment by villares** [comment]
@spprocessing please try Python mode build 3062!

**Comment by spprocessing** [comment]
Hi @villares,

Today I installed Python mode build 3062 as you suggested and, indeed, the sketch runs perfectly with it :)

Thank you all for your help and assistance, it was really important in my work. Thank you!
