### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [jdf/Processing.py-Bugs#338]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by processing.app.platform.LinuxPlatform (file:/home/appinv/Downloads/processing-4.0b2/lib/pde.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of processing.app.platform.LinuxPlatform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
created registry at port 8220
Traceback (most recent call last):
  File "/home/appinv/sketchbook/modes/PythonMode/formatter/format_server.py", line 12, in <module>
    sock.bind(server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Dec 24, 2021 2:46:46 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
could not create registry; assume it's already created
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PyJavaType (file:/home/appinv/sketchbook/modes/PythonMode/mode/jython.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.python.core.PyJavaType
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
could not create registry; assume it's already created
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PyJavaType (file:/home/appinv/sketchbook/modes/PythonMode/mode/jython.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.python.core.PyJavaType
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Linux Mint 20.2, Processing 4.0b2

Was just running  a very simple sketch.

**Comment by villares** [comment]
Cheers @Abdur-rahmaanJ 
Python mode is not working on Processing 4 yet. Please try 3.5.4!

**Comment by Abdur-rahmaanJ** [comment]
Ooooooh thanks ...
