### ISSUE TITLE
Python error in the latest version

### ISSUE THREAD

**Issue by dibyendu1** [jdf/Processing.py-Bugs#341]
While running any code in Python, the following error is encountered: 

java.lang.NullPointerException
	at jycessing.Runner.runSketchBlocking(Unknown Source)
	at jycessing.mode.run.SketchRunner.lambda$startSketch$3(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)

Software info:

Processing 4.0b3
OS: Ubuntu 20.04

**Comment by Chagomass** [comment]
I have the same error on a different setup : 

Processing 4.0b3
MacOS Big Sur (11.6)

I first had to authorise libjniosx.dylib manually, and then the same error message that OP sees appears in console.

Thanks ahead

**Comment by tabreturn** [comment]
At the moment, Python Mode isn't supported in Processing 4, but the developers are working on a solution. Use Processing 3.5.4 for now.

**Comment by dibyendu1** [comment]
> At the moment, Python Mode isn't supported in Processing 4, but the developers are working on a solution. Use Processing 3.5.4 for now.

Thank you for the suggestion. I will be using Processing 3.5.4 for now. Hope it get fixed soon.
