### ISSUE TITLE
PeasyCam do not import correctly

### ISSUE THREAD

**Issue by Aria-AAs** [jdf/Processing.py-Bugs#380]
I try to import "PeasyCam" library to my sketch but it raise this error

```
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at jycessing.LibraryImporter.addJarToClassLoader(LibraryImporter.java:315)
	at jycessing.LibraryImporter.recursivelyAddJarsToClasspath(LibraryImporter.java:164)
	at jycessing.LibraryImporter.addLibrary(LibraryImporter.java:140)
	at jycessing.LibraryImporter$1.__call__(LibraryImporter.java:82)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
	at org.python.pycode._pyx268.f$0(rubic_cube.pyde:1)
	at org.python.pycode._pyx268.call_function(rubic_cube.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.pycode._pyx267.f$0(C:/Users/aas/Desktop/rubic_cube/rubic_cube.pyde:96)
	at org.python.pycode._pyx267.call_function(C:/Users/aas/Desktop/rubic_cube/rubic_cube.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at jycessing.PAppletJythonDriver.processSketch(PAppletJythonDriver.java:233)
	at jycessing.PAppletJythonDriver.findSketchMethods(PAppletJythonDriver.java:613)
	at jycessing.Runner.runSketchBlocking(Runner.java:399)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:112)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by villares** [comment]
Hi @Aria-AAs 

I'm afraid [Processing Python Mode currently lacks a maintainer](https://discourse.processing.org/t/python-mode-needs-a-new-project-owner/36399).

If you, like me, enjoy using the Processing graphics vocabulary with Python, you can do it now with [py5](https://py5coding.org/), which uses Processing 4 jars, [many Processing Java libraries work, including PeasyCam](https://github.com/py5coding/py5generator/discussions/110)
