### ISSUE TITLE
java.lang.ClassCastException thrown when calling add_library(...)

### ISSUE THREAD

**Issue by tomsiw** [jdf/Processing.py-Bugs#381]
A call to add_library(...) always throws ClassCastException no mater which library I'm trying to add.
Callstack:
```
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at jycessing.LibraryImporter.addJarToClassLoader(LibraryImporter.java:315)
	at jycessing.LibraryImporter.recursivelyAddJarsToClasspath(LibraryImporter.java:164)
	at jycessing.LibraryImporter.addLibrary(LibraryImporter.java:140)
	at jycessing.LibraryImporter$1.__call__(LibraryImporter.java:82)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
        ...
```

Example code:

```
add_library('minim')
from ddf.minim import Minim, Controller
```

**Comment by RMMeerding** [comment]
I've got the same problem as 'tomsiw'. Trying to add Box2D and JBox2D in a way as suggested long time ago --https://forum.processing.org/two/discussion/25473/box2d-for-python-mode.html-- in order to explore chapter 5 in 'the Nature of Code' by Daniel Schiffman. But it doesn't work, all I get is the same java.lang.ClassCastException ...

**Comment by villares** [comment]
Hi @tomsiw and @RMMeerding!

I'm afraid [Processing Python Mode currently lacks a maintainer](https://discourse.processing.org/t/python-mode-needs-a-new-project-owner/36399), at this point. 

If you, like me, enjoy using the Processing graphics vocabulary with Python, you can do it with Python 3,  using [p5py](https://github.com/p5py/p5) (which is all new and does not depend on Processing/Java, you would need to use only libraries from the Python ecossystem) or [py5](https://py5coding.org/) (which uses Processing 4 jars, many Processing Java libraries work). 

For 2D Physics I use https://pymunk.org, for audio I'm still looking around.
