### ISSUE TITLE
Python mode doesn't work.

### ISSUE THREAD

**Issue by saltwater2015** [jdf/Processing.py-Bugs#387]
Win 11  home.
Processing 4.3.
 
I just tried a very simple code:
```
def setup():
    size(640, 360, P3D)
    fill(204)


def draw():
    lights()
    background(0)
```

But I got the following  output:
`java.lang.NullPointerException
	at jycessing.Runner.runSketchBlocking(Unknown Source)
	at jycessing.mode.run.SketchRunner.lambda$startSketch$3(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
`
But I am in the java mode. All things goes all right.
I cant run all types of Examples in the python mode. I got the same output as the above.

**Comment by saltwater2015** [comment]
I installed python mode for processing 4. in "modes"-"contribution manager". But I got another error report:
```
RemoteException occurred in server thread; nested exception is: 
	java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: 
	java.io.InvalidClassException: jycessing.mode.run.PdeSketch; local class incompatible: stream classdesc serialVersionUID = 3931972619109913057, local class serialVersionUID = 4088556615327966884

``` 

Does processing 4 still support python?

**Comment by villares** [comment]
> Does processing 4 still support python?

Hi @saltwater2015, I'm afraid Processing Python mode is an unmaintained project, not supported on Processing 4.

I recommend you check https://py5coding.org as the new (and better!) way of getting the Processing 4 graphics infrastructure with Python (now integrated into the  modern Python 3 ecosystem!).

If you'd like to get an experience close to the one with the Processing IDE (to make things easier for beginners) you could have a look at Thonny IDE (thonny.org) with the `thonny-py5mode` plug-in: https://abav.lugaralgum.com/como-instalar-py5/index-EN.html
